### ISSUE TITLE
Condition to apply sidebar to one specific page AND all this children

### ISSUE THREAD

**Issue by jlethuau** [woocommerce/woosidebars#24]
Hi and thanks for this plugin which saves me a lot of time in many projects.

It would be great to add a feature to create conditions like:
- for the page XXX and all its children

Now if I chose one page in the "Page" condition tab, the sidebar only changes on this page and not for the clidren. It can be done by selecting all subpages but for future pages, its not easy.

Besides, display the hierarchy into this "Page tab" would be great!

Regards

**Comment by jselite** [comment]
Hi, very interested in this too please :)

**Comment by EireStudio** [comment]
Hi, any update on this?

**Comment by jeffikus** [comment]
@EireStudio - no immediate plans for this, but as soon as it has been scheduled, you will see the milestone change and a dev will be assigned to the ticket.

**Comment by znagle** [comment]
Any idea if this will ever be scheduled?

**Comment by mattyza** [comment]
@znagle it will be scheduled, yes.

This is also a great issue for a first contribution. If you'd like to submit a pull request, we'd appreciate it, and would be glad to review.

**Comment by javorszky** [comment]
Hi all,

There's a PR in to add this functionality to the plugin. If you can, please give it a spin, and let me know whether that works for you or not!
