### ISSUE TITLE
Incompatible with 4.6.1 

### ISSUE THREAD

**Issue by dimbak** [woocommerce/woosidebars#52]
Hi, i tried to use the plugin with the default 2015 theme and no luck.I can see the sidebar created but i don't see the widgets on the front end.

I don't get any messages either with WP_DEBUG = on

**Comment by mattyza** [comment]
Hi @dimbak.

Myself and a few of our Happiness Engineers have tested this, and all looks to be in order.

Have you perhaps set a complex set of conditions for the widget area replacement, or perhaps not added widgets to your new custom widget area?

**Comment by dimbak** [comment]
Hi, i see it now working with Storefront but did you update it? in https://wordpress.org/plugins/woosidebars/changelog/ i see it was updated 1 day ago but the changelog says '1.4.3
2015-09-22
Ensures condition headings are present before attempting to output in the conditions meta box.'

**Comment by mattyza** [comment]
@dimbak - The update was to adjust the compatibility tag in the repository. No code changes were made, so no version bump is necessary.

I'm glad to hear it's now working on your WordPress 4.6.1 installation as well. :)

**Comment by dimbak** [comment]
Really weird i had problems before, good that its working again.Sorry for the trouble.

**Comment by mattyza** [comment]
No trouble at all. :)
