### ISSUE TITLE
Notice on class-woo-sidebars.php on line 743

### ISSUE THREAD

**Issue by webdados** [woocommerce/woosidebars#61]
`( ! ) Notice: Trying to get property of non-object in /Users/marcoalmeida/Documents/Websites/www.wordpress.dev/wp-content/plugins/woosidebars/classes/class-woo-sidebars.php on line 743`

I got this just after setting up the Flatsome theme.

**Comment by jeffikus** [comment]
On what screen exactly does this occur? I know the theme, does this happen immediately when you click the Activate button to switch to the theme or on another screen?

**Comment by webdados** [comment]
When you finish their wizard, I think on the same screen they suggest to take the WooCommerce wizard.

Anyway, it's just a matter of testing `get_current_screen()->id` with `is_callable`, I guess.

**Comment by mattyza** [comment]
Resolved in #56
