### ISSUE TITLE
Release a new version of the wooSidebars plugin

### ISSUE THREAD

**Issue by snrbrnjna** [woocommerce/woosidebars#66]
Hi there!

I can't use the latest merges #57 and #60 🎉 as there is no new release of the woosidebars plugin in the wordpress plugin site (https://wordpress.org/plugins/woosidebars/), hence i cant fetch them via composer (https://wpackagist.org/search?q=woosidebars).

So please release it and I'm happy ;)

**Comment by snrbrnjna** [comment]
ping @mattyza

**Comment by mattyza** [comment]
Thanks for pinging, @snrbrnjna. I'll be sure to prep and tag a release within the next week.

**Comment by snrbrnjna** [comment]
hi @mattyza i'm still waiting for the new version 🌵

**Comment by mattyza** [comment]
@snrbrnjna Sorry for the delay here. The latest release can be found here: https://github.com/woocommerce/woosidebars/releases/tag/version%2F1.4.4

This will be pushed to WordPress.org on Monday.
